//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleBased.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_Role = new HashSet<tbl_Role>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        public virtual ICollection<tbl_Role> tbl_Role { get; set; }
    }
}
